export const words = [
  "chat","chien","cheval","lapin","souris","éléphant","girafe","lion","tigre","ours",
  "renard","loup","singe","kangourou","pingouin","dauphin","baleine","requin","poisson","crabe",
  "poulpe","escargot","papillon","abeille","araignée","fourmi","hibou","aigle","perroquet","canard",
  "poule","cochon","vache","mouton","chèvre","tortue","grenouille","serpent","crocodile","zèbre",
  "maison","appartement","château","cabane","tente","pont","tour","phare","moulin","église",
  "porte","fenêtre","escalier","cheminée","toit","clôture","jardin","piscine","balcon","garage",
  "voiture","vélo","train","avion","bateau","bus","moto","camion","fusée","montgolfière",
  "hélicoptère","tracteur","trottinette","skateboard","métro","ambulance","taxi","sous-marin","voilier","charrette",
  "soleil","lune","étoile","nuage","pluie","neige","arc-en-ciel","éclair","tornade","volcan",
  "montagne","forêt","rivière","océan","désert","île","cascade","grotte","falaise","plage",
  "arbre","fleur","cactus","champignon","feuille","herbe","sapin","tulipe","rose","tournesol",
  "pomme","banane","fraise","orange","raisin","ananas","pastèque","citron","cerise","poire",
  "carotte","tomate","pomme de terre","citrouille","brocoli","champignon de paris","oignon","maïs","poivron","concombre",
  "pain","fromage","gâteau","pizza","hamburger","glace","chocolat","biscuit","croissant","crêpe",
  "café","thé","lait","œuf","miel","beurre","sucre","sel","riz","pâtes",
  "table","chaise","lit","canapé","armoire","miroir","lampe","horloge","tapis","étagère",
  "livre","stylo","crayon","ciseaux","gomme","cahier","règle","carte","enveloppe","timbre",
  "téléphone","ordinateur","télévision","appareil photo","radio","montre","clavier","souris d'ordinateur","imprimante","casque audio",
  "chapeau","chaussure","botte","gant","écharpe","lunettes","parapluie","sac à main","ceinture","cravate",
  "robe","pantalon","chemise","manteau","chaussette","pyjama","costume","tablier","short","gilet",
  "soleil couchant","arc","flèche","épée","bouclier","couronne","clé","cadenas","échelle","corde",
  "ballon","balle","raquette","filet","dé","cartes à jouer","échiquier","puzzle","toupie","cerf-volant",
  "guitare","piano","violon","tambour","flûte","trompette","harpe","microphone","haut-parleur","métronome",
  "docteur","pompier","policier","cuisinier","professeur","astronaute","pirate","chevalier","clown","magicien",
  "peintre","musicien","fermier","pêcheur","facteur","boulanger","dentiste","vétérinaire","jardinier","plombier",
  "robot","fantôme","dragon","sorcière","vampire","licorne","sirène","géant","extraterrestre","zombie",
  "cœur","sourire","larme","empreinte","ombre","reflet","tornade de sable","boussole","carte au trésor","loupe",
  "valise","appareil dentaire","brosse à dents","savon","serviette","peigne","miroir de poche","parapluie de plage","tongs","maillot de bain",
  "neige fondue","bonhomme de neige","traîneau","patin à glace","ski","igloo","sapin de noël","cadeau","bougie","feu d'artifice",
  "moulin à vent","épouvantail","meule de foin","charrue","silo","étable","poulailler","ruche","serre","panier"

];
